COMMON:
  DATA_PATH: data
  TRAINING: True # 训练是True,test改为False
TRAIN:
  TRAIN_DATA_PATH: train
  BATCH_SIZE: 1
  PRETRAIN: pretrain
  CKPT: checkpoints
  RESTORE: False
  MAX_ITER: 500
  LEARNING_RATE: 0.00001
  SOLVER: Adam
  MOMENTUM: 0.9

